from . import config
from . import datos
from . import ruc
from . import desvincularruc
from . import contrato
from . import plan
from . import eliminarplan
from . import plandinamico
from . import personal
from . import vincularpersonal
from . import eliminarpersonal
from . import habilidades
from . import material
from . import eliminarmaterial
from . import catalogoticket
from . import eliminarcatalogoticket
from . import imprimir
from . import cajasave
from . import cajaeliminar
from . import cajavincular
